### ISSUE TITLE
PRs/issues for stable release with 300 cell examples

### ISSUE THREAD

**Issue by pgleeson** [AllenInstitute/sonata#103]
To ensure 300_pointneurons and 300_cells work across the various implementing packages:

- [ ] Sonata branch merged into NetPyNE development https://github.com/Neurosim-lab/netpyne/pull/420 (@salvadord)
- [ ] Merge [sonata branch](https://github.com/NeuralEnsemble/PyNN/tree/sonata) into PyNN master (@apdavison )
- [ ] Record selected cells in 300 detailed network: https://github.com/AllenInstitute/sonata/issues/99 (@kaeldai)
- [ ] Minor changes for testing BMTK https://github.com/AllenInstitute/bmtk/pull/73/files (@kaeldai) 
- [ ] Test suite & various example updates/tests: https://github.com/AllenInstitute/sonata/pull/100 (@kaeldai)
- [ ] static_synapse -> nest:static_synapse: https://github.com/AllenInstitute/sonata/issues/102 (@kaeldai) 
- [ ] Document Sonata -> NeuroML, add it here https://github.com/AllenInstitute/sonata/issues/97 (@pgleeson)
